### ISSUE TITLE
Conform to Dockerflow spec

### ISSUE THREAD

**Issue by milescrabill** [mozilla/speech-proxy#17]
The spec can be found here: https://github.com/mozilla-services/dockerflow

I PR'd for:
* Listen on environment variable $PORT for HTTP requests.
* Must have a JSON version object at /app/version.json. (created as part of CircleCI build step, copied into container)

**Comment by wresuolc** [comment]
@milescrabill to review and close

**Comment by andrenatal** [comment]
I just reviewed both the dockerfile and the app requirements and we are complying with all of them. So I am closing this.

**Comment by milescrabill** [comment]
lgtm as well
