### ISSUE TITLE
Error when I run the proxy locally with firejail enabled

### ISSUE THREAD

**Issue by andrenatal** [mozilla/speech-proxy#30]
```
/usr/bin/node --inspect-brk=43071 /home/andre/voicefill/speech-proxy/server.js
Debugger listening on ws://127.0.0.1:43071/84da981b-5f3e-4d6c-81a6-7ce2f7a9990c
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
HTTP and BinaryJS server started on port 9001
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:851:14)
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:43071/84da981b-5f3e-4d6c-81a6-7ce2f7a9990c
For help see https://nodejs.org/en/docs/inspector
```

**Comment by andrenatal** [comment]
@g-k any idea?

**Comment by g-k** [comment]
@andrenatal Is the debugger running in the container? If so, is the debugger port exposed? Are there listeners for the error event on the stdout and stderr streams of the opusdec call?

**Comment by andrenatal** [comment]
@g-k I am facing this issue when I run in my computer, and not in the container.

**Comment by andrenatal** [comment]
@g-k I just built a new container and am now getting this error when a request is made:

```
Reading profile opusdec.profile
DISPLAY is not set
Error clone: main.c:2388 main: Operation not permitted
```

**Comment by andrenatal** [comment]
Interesting that when I run in my local ubuntu, the error changes to:

```
HTTP and BinaryJS server started on port 9001
Reading profile opusdec.profile
Error: line 21 in opusdec.profile is invalid
```

**Comment by andrenatal** [comment]
Yeah, seems the `Error: write EPIPE` only happens when the debugger is running.

**Comment by g-k** [comment]
I only expect this to work when run with the container using `--privileged` i.e. `make build run`. How're you running it when you see these errors?

**Comment by andrenatal** [comment]
@g-k yes, when I run it with --privileged it works! Thank you!
