### ISSUE TITLE
Documentation / Guide for using with web app?

### ISSUE THREAD

**Issue by mscreenie** [mozilla/speech-proxy#49]
**Suggestion**

A basic web demo showing off this project to provide real time Speech to Text inside a web application?

e.g. https://speech-to-text-demo.mybluemix.net/

- Utilize websockets/webrtc
- Show how results are formatted ?
- Compare with other paid speech services. (Accuracy, latency etc)

This would be a really nice demo and I think might be within the scope of this project. In my case I was looking for a ASR/Speech to Text self hosted solution for a project I am working on and I came across this. 

The options were either Google / Amazon Alexa and others, prices are not within budget, hosting on empty or spare resources is easier.

**Comment by andrenatal** [comment]
You can use our endpoint if you want. Here is an easy demo app: https://github.com/andrenatal/speak-to-me-demo/tree/master

**Comment by andrenatal** [comment]
Hi @mscreenie , you can use our js module to speech enable your webapp:

https://www.npmjs.com/package/speaktome-api
