### ISSUE TITLE
Ensure Opus processing is sandboxed

### ISSUE THREAD

**Issue by wresuolc** [mozilla/speech-proxy#6]
@oremj is working on a solution to this

**Comment by jvehent** [comment]
We're evaluating this in https://github.com/mozilla-services/foxsec/issues/346
So far, it looks like keeping the call to `opusdec` as an execve is the best option, as it would allow us to wrap it inside a `firejail`.

cc @g-k

**Comment by andrenatal** [comment]
Seems I don't have access to mentioned issue, @jvehent. So please just let me know when you guys have made a decision about what I should change.

**Comment by g-k** [comment]
@wresuolc This fixes the issue. I have some related follow up issues, but they can be tracked separately.

**Comment by wresuolc** [comment]
Great, thank you!
