### ISSUE TITLE
UA string sent by Firefox not matching the UA regex validator 

### ISSUE THREAD

**Issue by andrenatal** [mozilla/speech-proxy#69]
Hi @g-k ,

we deployed the backend to staging and in our tests we found this UA being sent by Firefox:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0`

that did not match the Regex: 

`const regexUA = RegExp('^[a-zA-Z0-9-_ \t\\\/\.;:]{0,1024}$');`

consequently blocking a valid request. Seems the parenthesis are the culprit:

> mac:~ anatal$ node
> const regexUA = RegExp('^[a-zA-Z0-9-_ \t\\\/\.;:]{0,1024}$');
> regexUA.test('Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0')
false
> regexUA.test('Mozilla/5.0 Macintosh; Intel Mac OS X 10.13; rv:62.0 Gecko/20100101 Firefox/62.0')
> true

Do you have any suggestion? I'm concerned about what we can find in the wild that will inadvertently block requests :(

**Comment by g-k** [comment]
So it should be fine to whitelist parens `()`, but if you anticipate this happening with more characters then we could also just store everything as is and try to be more careful about how we handle the UA data.

**Comment by mrstegeman** [comment]
UA strings can really be anything at all. Parsing with a single regex seems kind of wrong. There are several libraries that can help with this, for example: [ua-parser-js](https://www.npmjs.com/package/ua-parser-js).

**Comment by andrenatal** [comment]
Yeah, let's remove the UA validation and just store it as hex.

**Comment by andrenatal** [comment]
Fixed
